### ISSUE TITLE
time_first error in pDNS transform

### ISSUE THREAD

**Issue by krmaxwell** [digital4rensics/Malformity#6]
Occasionally get the following error.

``` XML
<MaltegoMessage><MaltegoTransformExceptionMessage><Exceptions><Exception>Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/canari-0.5-py2.7.egg/canari/commands/run_transform.py", line 102, in run
    MaltegoTransformResponseMessage()
  File "/usr/local/lib/python2.7/dist-packages/Malformity-1.0-py2.7.egg/Malformity/transforms/pDNS_IP2Domain.py", line 40, in dotransform
    first = data['time_first']
KeyError: 'time_first'
</Exception></Exceptions></MaltegoTransformExceptionMessage></MaltegoMessage>
```

**Comment by digital4rensics** [comment]
Fixed with latest commit. Thanks!
